apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: core_platform-mesh_io_account
  name: account-accounts
spec:
  inlineConfiguration:
    content: |-
      {
          "name": "accounts",
          "creationTimestamp": "2022-05-17T11:37:17Z",
          "luigiConfigFragment": {
              "data": {
                  "nodes": [
                      {
                          "pathSegment": "accounts",
                          "navigationContext": "accounts",
                          "label": "Accounts",
                          "icon": "product",
                          "order": 300,
                          "entityType": "main.core_platform-mesh_io_account",
                          "loadingIndicator": {
                              "enabled": false
                          },
                          "keepSelectedForChildren": true,
                          "url": "/assets/platform-mesh-portal-ui-wc.js#generic-list-view",
                          "webcomponent": {
                              "selfRegistered": true
                          },
                          "children": [
                              {
                                  "pathSegment": ":core_platform-mesh_io_accountId",
                                  "hideFromNav": true,
                                  "keepSelectedForChildren": false,
                                  "defineEntity": {
                                      "id": "core_platform-mesh_io_account",
                                      "type": "account",
                                      "contextKey": "core_platform-mesh_io_accountId",
                                      "dynamicFetchId": "core_platform-mesh_io_account",
                                      "additionalContextKeys": ["accountPath"]
                                  },
                                  "context": {
                                      "accountId": ":core_platform-mesh_io_accountId",
                                      "core_platform-mesh_io_accountId": ":core_platform-mesh_io_accountId",
                                      "resourceId": ":core_platform-mesh_io_accountId"
                                  },
                                  "navHeader": {
                                    "label": ":core_platform-mesh_io_accountId"
                                  }
                              }
                          ]
                      }
                  ]
              }
          }
      }
    contentType: json
