apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.platform-mesh.io
spec:
  latestResourceSchemas:
  - v260126-7c674ee.accountinfos.core.platform-mesh.io
  - v260109-82344be.accounts.core.platform-mesh.io
  - v250704-6d57f16.contentconfigurations.ui.platform-mesh.io
  - v250725-732d200.providermetadatas.ui.platform-mesh.io
  - v260112-5925c7e.authorizationmodels.core.platform-mesh.io
  - v250718-a64f278.stores.core.platform-mesh.io
  - v260212-65a62b6.invites.core.platform-mesh.io
  - v260123-dbda1fc.identityproviderconfigurations.core.platform-mesh.io
  permissionClaims:
    - all: true
      group: tenancy.kcp.io
      identityHash: {{ .apiExportRootTenancyKcpIoIdentityHash }}
      resource: workspaces
    - all: true
      group: tenancy.kcp.io
      identityHash: {{ .apiExportRootTenancyKcpIoIdentityHash }}
      resource: workspacetypes
    - resource: apibindings
      group: apis.kcp.io
      all: true
      identityHash: ""
    - resource: apiexports
      group: apis.kcp.io
      all: true
      identityHash: ""
    - resource: apiresourceschemas
      group: apis.kcp.io
      all: true
      identityHash: ""
    - resource: logicalclusters
      group: core.kcp.io
      all: true
      identityHash: ""
    - resource: secrets
      group: ""
      all: true
      identityHash: ""
status: {}
