apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: search.platform-mesh.io
spec:
  permissionClaims:
    - all: true
      group: ""
      resource: search

status: {}
