apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: core_platform-mesh_io_account
  name: account-home
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "overview",
        "creationTimestamp": "2022-05-17T11:37:17Z",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "entityType": "main.core_platform-mesh_io_account",
                "pathSegment": "dashboard",
                "label": "Dashboard",
                "icon": "bbyd-dashboard",
                "order": 100,
                "url": "/assets/platform-mesh-portal-ui-wc.js#generic-detail-view",
                "webcomponent": {
                  "selfRegistered": true
                },
                "defineEntity": {
                    "id": "dashboard"
                },
                "compound": {
                    "children": []
                }
              }
            ]
          }
        }
      }
    contentType: json
