apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: main
  name: main-marketplace
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "marketplace",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "pathSegment": "marketplace",
                "entityType": "main",
                "label": "Marketplace",
                "order": 700,
                "icon": "retail-store",
                "hideFromNav": false,
                "url": "https://{context.organization}.{{ .baseDomainPort }}/ui/marketplace/ui/#/entity/org/marketplace",
                "viewGroup": "marketplace",
                "context": {
                  "entityContext": {
                    "account": {
                      "policies": ["providerAdmin", "projectAdmin", "projectMember"]
                    }
                  }
                }
              },
              {
                "pathSegment": "provider",
                "entityType": "main",
                "hideFromNav": true,
                "viewGroup": "marketplace",
                "children": [
                  {
                    "pathSegment": ":providerName",
                    "hideFromNav": true,
                    "url": "https://{context.organization}.{{ .baseDomainPort }}/ui/marketplace/ui/#/provider/:providerName",
                    "context": {
                      "providerName": ":providerName"
                    }
                  }
                ],
                "context": {
                  "entityContext": {
                    "account": {
                      "policies": ["providerAdmin", "projectAdmin", "projectMember"]
                    }
                  }
                }
              }
            ],
            "texts": [
              {
                "locale": "",
                "textDictionary": {
                  "marketplace": "Marketplace"
                }
              },
              {
                "locale": "en",
                "textDictionary": {
                  "marketplace": "Marketplace"
                }
              },
              {
                "locale": "de",
                "textDictionary": {
                  "marketplace": "Marktplatz"
                }
              }
            ]
          }
        }
      }
    contentType: json
