apiVersion: core.platform-mesh.io/v1alpha1
kind: IdentityProviderConfiguration
metadata:
  name: welcome
spec:
  clients:
  - clientType: confidential
    clientName: welcome
    redirectUris:
    - https://portal.localhost:8443/callback*
    secretRef:
      name: portal-client-secret-welcome
      namespace: default
  - clientType: public
    clientName: welcome-kubectl
    redirectUris:
      - http://localhost:8000/*
      - http://localhost:18000/*
    secretRef:
      name: welcome-kubectl-client-secret
      namespace: default