# permissions for end users to edit platformmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: platform-mesh-operator
    app.kubernetes.io/managed-by: kustomize
  name: platform-mesh-editor-role
rules:
- apiGroups:
  - core.platform-mesh.io
  resources:
  - platformmeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.platform-mesh.io
  resources:
  - platformmeshes/status
  verbs:
  - get
