{{- if and .gatewayApi.enabled (eq .deploymentTechnology "argocd") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .gatewayApi.name }}
  namespace: {{ .helmReleaseNamespace }}
  labels:
    core.platform-mesh.io/operator-created: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .gatewayApi.syncWave | default 0 }}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-mesh-runtime
  {{- if .gatewayApi.ignoreDifferences }}
  ignoreDifferences:
{{ toYaml .gatewayApi.ignoreDifferences | nindent 4 }}
  {{- end }}
  source:
    {{- if and .gatewayApi.repoURL (ne .gatewayApi.repoURL "") }}
    repoURL: {{ .gatewayApi.repoURL }}
    {{- else }}
    repoURL: PLACEHOLDER_TO_BE_SET_BY_RESOURCE_SUBROUTINE
    {{- end }}
    {{- if and .gatewayApi.kustomization .gatewayApi.kustomization.path }}
    path: {{ .gatewayApi.kustomization.path }}
    {{- else }}
    path: PLACEHOLDER_TO_BE_SET_BY_RESOURCE_SUBROUTINE
    {{- end }}
    {{- if and .gatewayApi.targetRevision (ne .gatewayApi.targetRevision "") }}
    targetRevision: {{ .gatewayApi.targetRevision }}
    {{- else }}
    targetRevision: PLACEHOLDER_TO_BE_SET_BY_RESOURCE_SUBROUTINE
    {{- end }}
  destination:
    server: {{ .destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .releaseNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    {{- if .gatewayApi.syncOptions }}
    syncOptions:
{{ toYaml .gatewayApi.syncOptions | nindent 4 }}
    {{- else }}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    {{- if .gatewayApi.ignoreDifferences }}
    - RespectIgnoreDifferences=true
    {{- end }}
    {{- if and .gatewayApi.kustomization .gatewayApi.kustomization.install .gatewayApi.kustomization.install.crds (eq .gatewayApi.kustomization.install.crds "Skip") }}
    - SkipDryRunOnMissingResource=true
    {{- end }}
    {{- end }}
{{- end }}

