{{- if .certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .certManager.name }}
  namespace: {{ .helmReleaseNamespace }}
  labels:
    core.platform-mesh.io/operator-created: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .certManager.syncWave | default 0 }}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-mesh-runtime
  source:
    {{- if .certManager.repoURL }}
    repoURL: {{ .certManager.repoURL }}
    {{- else }}
    repoURL: https://charts.jetstack.io
    {{- end }}
    chart: cert-manager
    targetRevision: "*"
    {{- if .certManager.values }}
    helm:
      values: |
{{ toYaml .certManager.values | nindent 8 }}
    {{- end }}
  destination:
    server: {{ .destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .releaseNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}

