{{- if .certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .certManager.name }}
  namespace: {{ .helmReleaseNamespace }}
  labels:
    core.platform-mesh.io/operator-created: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .certManager.syncWave | default 0 }}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-mesh-runtime
  {{- if .certManager.ignoreDifferences }}
  ignoreDifferences:
{{ toYaml .certManager.ignoreDifferences | nindent 4 }}
  {{- end }}
  source:
    {{- if .certManager.repoURL }}
    repoURL: {{ .certManager.repoURL }}
    {{- else }}
    repoURL: https://charts.jetstack.io
    {{- end }}
    chart: cert-manager
    targetRevision: "*"
    {{- if or .certManager.values .certManager.skipCrds }}
    helm:
      {{- if .certManager.skipCrds }}
      skipCrds: true
      {{- end }}
      {{- if .certManager.values }}
      values: |
{{ toYaml .certManager.values | nindent 8 }}
      {{- end }}
    {{- end }}
  destination:
    server: {{ .destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .releaseNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    {{- if .certManager.syncOptions }}
    syncOptions:
{{ toYaml .certManager.syncOptions | nindent 4 }}
    {{- else }}
    syncOptions:
    - CreateNamespace=true
    {{- if .certManager.ignoreDifferences }}
    - RespectIgnoreDifferences=true
    {{- end }}
    {{- end }}
{{- end }}

